### ISSUE TITLE
issue and advice

### ISSUE THREAD

**Issue by francisLee777** [vision9527/btree#1]
1.   向外暴露的添加元素接口，入参是 interface， 如果传一个数组或者map，或者包含的 struct ，都会导致内部做 == 判断的时候panic。 可以前置判断，提前返回。
2.   在插入元素导致节点分裂之前，应该先执行B+树的 rotate 操作，可以提高性能，减少不必要的分裂操作。

**Comment by vision9527** [comment]
谢谢提供意见
对于第一个问题，可以举个具体例子吗？
对于第二个问题，在性能上没有去考虑，目前只是做一个基本算法实现，也没有做benchmark（后面如果有空的话可能会考虑做一些更多的优化和功能），如果有兴趣可以提交mr

**Comment by vision9527** [comment]
> 1. 向外暴露的添加元素接口，入参是 interface， 如果传一个数组或者map，或者包含的 struct ，都会导致内部做 == 判断的时候panic。 可以前置判断，提前返回。
> 2. 在插入元素导致节点分裂之前，应该先执行B+树的 rotate 操作，可以提高性能，减少不必要的分裂操作。

谢谢提供意见
对于第一个问题，可以举个具体例子吗？
对于第二个问题，在性能上没有去考虑，目前只是做一个基本算法实现，也没有做benchmark（后面如果有空的话可能会考虑做一些更多的优化和功能），如果有兴趣可以提交mr
